export const VENDORS = {
  "Blue Pepper Cuisine": {
    emoji: "🫑",
    location: "Student Center",
    hours: { "Mon–Fri": "9am–8pm", "Sat–Sun": "Closed" },
    tags: ["Vegetarian", "Vegan options", "Thai-inspired"],
    deals: [
      "Fresh, quality Thai and Asian dishes",
      "Strong healthy option at Student Center",
    ],
    phone: "(858) 203-3654",
    website: "https://www.bluepepperucsd.com",
    dietary: ["Vegetarian", "Vegan"],
    color: "#0277BD",
  },
  "Burger King": {
    emoji: "🍔",
    location: "Price Center, Level 1",
    hours: { "Mon–Thu": "Open 24 hrs", "Fri": "7am–12am", "Sat": "8am–12am", "Sun": "9:30am–12am" },
    tags: ["24hr Mon–Thu", "Late night"],
    deals: [
      "Only 24-hr food option on campus Mon–Thu",
      "Late-night fallback all week",
      "App deals via BK app",
    ],
    phone: "(858) 247-0498",
    website: "https://www.bk.com",
    dietary: [],
    color: "#D32F2F",
  },
  "Croutons": {
    emoji: "🥙",
    location: "Student Services Center, Level 2",
    hours: { "Mon–Fri": "10am–3pm", "Sat–Sun": "Closed" },
    tags: ["Vegetarian", "Lunch only"],
    deals: [
      "Lunch-only — quick midday option",
      "Fresh salads and soups made to order",
      "Panini options",
    ],
    phone: "(858) 450-0240",
    website: "http://www.croutonstogo.com",
    dietary: ["Vegetarian"],
    color: "#6D4C41",
  },
  "Curry Up Now": {
    emoji: "🍛",
    location: "Price Center",
    hours: { "Mon–Thu": "10am–10pm", "Fri": "10am–9pm", "Sat–Sun": "11am–8pm" },
    tags: ["Vegetarian", "Vegan", "Halal", "Keto/Paleo"],
    deals: [
      "Tikka Masala burrito — signature fusion must-try",
      "Holy Moly Fried Ravioli",
      "Itsy Bitsy Naan Bites + Samosas",
      "Open late — until 10pm Mon–Thu",
    ],
    phone: "(858) 780-5030",
    website: "https://order.thanx.com/curryupnow",
    dietary: ["Vegetarian", "Vegan", "Halal", "Keto", "Paleo"],
    color: "#F57C00",
  },
  "Dirty Birds": {
    emoji: "🍗",
    location: "Price Center",
    hours: { "Mon–Fri": "10am–9:30pm", "Sat–Sun": "12pm–5pm" },
    tags: ["Alcohol served", "Outdoor patio"],
    deals: [
      "Daily combos 11am–3pm: food + soda deals",
      "Half-priced wings at select daily times",
      "Cheaper pizzas on special days",
      "$3 mimosas on weekends",
      "Tuesday = all-day happy hour",
      "27 wing flavors on campus",
      "Rotating beers on draft + wine",
    ],
    phone: "(858) 750-2121",
    website: "https://www.dirtybirdsbarandgrill.com",
    dietary: [],
    color: "#BF360C",
  },
  "FlavorFull": {
    emoji: "🥗",
    location: "Price Center",
    hours: { "Mon–Fri": "10am–8pm", "Sat": "11am–6pm", "Sun": "11am–8pm" },
    tags: ["Vegetarian"],
    deals: [
      "Hearty bowls, wraps, and salads",
      "Good dietary variety — lighter alternative",
    ],
    phone: "(858) 203-3364",
    website: "https://www.myflavorfull.com",
    dietary: ["Vegetarian"],
    color: "#388E3C",
  },
  "Food Co-op": {
    emoji: "🌱",
    location: "Student Center",
    hours: {},
    tags: ["Non-profit", "Vegetarian", "Vegan", "Student-run"],
    deals: [
      "Non-profit student-run — lowest prices on campus",
      "Vegetarian + vegan foods",
      "Natural and homeopathic health items",
    ],
    phone: "(858) 546-8339",
    website: "https://www.instagram.com/foodcoopatucsd",
    dietary: ["Vegetarian", "Vegan"],
    color: "#2E7D32",
  },
  "Jamba": {
    emoji: "🥤",
    location: "Price Center",
    hours: { "Mon–Sat": "9am–7pm", "Sun": "Closed" },
    tags: ["Vegetarian", "Vegan options"],
    deals: [
      "Energy bowls + fresh smoothies",
      "Steel-cut oatmeal — good breakfast option",
      "All-natural baked goods",
    ],
    phone: "(858) 622-2020",
    website: "https://locations.jamba.com/ca/la-jolla/9500-gilman-dr",
    dietary: ["Vegetarian", "Vegan"],
    color: "#7B1FA2",
  },
  "Lemongrass": {
    emoji: "🌿",
    location: "Price Center",
    hours: { "Mon–Thu": "9am–8pm", "Fri": "9am–6pm", "Sat": "10am–3pm", "Sun": "Closed" },
    tags: ["Vegetarian", "Thai fusion"],
    deals: [
      "Thai comfort dishes with fresh seasonal produce",
      "Opens at 9am Mon–Thu — early lunch window",
    ],
    phone: "(858) 455-6465",
    website: "https://www.lemongrassplates.com",
    dietary: ["Vegetarian"],
    color: "#558B2F",
  },
  "Multiple / Roundup": {
    emoji: "🗺️",
    location: "Various locations",
    hours: {},
    tags: ["Roundup post"],
    deals: ["Multi-vendor roundup — see post details"],
    phone: "",
    website: "",
    dietary: [],
    color: "#546E7A",
  },
  "Panda Express": {
    emoji: "🐼",
    location: "Price Center",
    hours: { "Mon–Fri": "9am–8pm", "Sat": "10am–6pm", "Sun": "Closed" },
    tags: [],
    deals: [
      "Plate combos: 2 sides + 1 entrée",
      "Family Feast options for groups",
      "Rewards via Panda Express app",
    ],
    phone: "(858) 638-0106",
    website: "https://www.pandaexpress.com",
    dietary: [],
    color: "#C62828",
  },
  "Santorini Greek Island Grill": {
    emoji: "🫙",
    location: "Price Center",
    hours: { "Mon–Fri": "8am–9pm", "Sat": "10am–6pm", "Sun": "11am–8pm" },
    tags: ["Vegetarian", "Vegan options"],
    deals: [
      "Falafel, gyros, fresh salads",
      "Opens at 8am — earliest savory option",
      "Open Sundays + late weekdays until 9pm",
    ],
    phone: "(858) 622-0067",
    website: "http://santoriniislandgrill.net/locations",
    dietary: ["Vegetarian", "Vegan"],
    color: "#1565C0",
  },
  "Shores Diner": {
    emoji: "🍝",
    location: "Student Center",
    hours: { "Mon–Fri": "10am–9pm", "Sat–Sun": "Closed" },
    tags: ["Alcohol served", "24 beers on tap"],
    deals: [
      "24 beers on tap + soju cocktails + wine",
      "Spaghetti, homemade meatballs, homemade chili",
      "Classic sandwiches + comfort food",
      "Same ownership as Dirty Birds — consistent quality",
    ],
    phone: "(858) 999-0018",
    website: "https://www.shoresdiner.com",
    dietary: [],
    color: "#37474F",
    inactive: true,
  },
  "Starbucks": {
    emoji: "☕",
    location: "Price Center",
    hours: { "Mon–Thu": "7am–8:30pm", "Fri": "7am–8pm", "Sat": "7am–6pm", "Sun": "9am–6pm" },
    tags: ["Open 7 days"],
    deals: [
      "Starbucks Rewards app accepted",
      "Student art gallery wall inside",
      "Early weekends — open 7am Saturday",
    ],
    phone: "(858) 534-5562",
    website: "https://www.starbucks.com",
    dietary: [],
    color: "#1B5E20",
    inactive: true,
  },
  "Su Pan Bakery": {
    emoji: "🍞",
    location: "Price Center Level 1, Y Mas (next to BK)",
    hours: { "Mon–Fri": "7am–3pm", "Sat–Sun": "Closed" },
    tags: ["Local family-owned", "Vegetarian", "Hidden gem"],
    deals: [
      "Made-from-scratch conchas, pan dulce, galletas",
      "Flan custards, fruit tarts, cochinitos",
      "Only local panadería on campus",
      "Easy to miss — tucked next to Burger King",
    ],
    phone: "(619) 287-2078",
    website: "https://www.supanbakery.com/en",
    dietary: ["Vegetarian"],
    color: "#E65100",
  },
  "Subway": {
    emoji: "🥖",
    location: "Price Center",
    hours: { "Mon–Thu": "7am–1am", "Fri": "7am–11pm", "Sat": "8am–11pm", "Sun": "9:30am–11pm" },
    tags: ["Open until 1am Mon–Thu", "Vegetarian"],
    deals: [
      "Best open-until-1am option Mon–Thu",
      "Subway Series + meal deals via app",
      "Footlong promos rotate through app",
    ],
    phone: "(858) 638-8275",
    website: "https://www.subway.com",
    dietary: ["Vegetarian"],
    color: "#33691E",
  },
  "Sunshine Market": {
    emoji: "🛒",
    location: "Price Center East",
    hours: { "Mon–Fri": "7am–8pm", "Sat–Sun": "10am–5pm" },
    tags: ["Accepts EBT", "Accepts Dining Dollars", "Just Walk Out"],
    deals: [
      "Amazon Just Walk Out — no checkout line",
      "Pachamama barista bar: coffee, teas, mocktails",
      "Signature 'Rise and Sunshine' drink",
      "Triton on the Go: fresh daily salads, sandwiches, sushi",
      "BCB Bagels + Mary's Donuts inside",
      "Loyalty Club: free hot drink every 10 purchases",
    ],
    phone: "(858) 534-4248",
    website: "https://hdh-web.ucsd.edu/dining/apps/diningservices",
    dietary: ["Vegetarian", "Vegan"],
    color: "#F9A825",
  },
  "Taco Bell": {
    emoji: "🌮",
    location: "Price Center",
    hours: { "Mon–Thu": "7am–1am", "Fri": "7am–11pm", "Sat": "8am–11pm", "Sun": "9:30am–11pm" },
    tags: ["Open until 1am Mon–Thu", "Vegan options"],
    deals: [
      "Cravings Value Menu — items under $3",
      "Combo meals + app deals",
      "Rewards: earn points per dollar spent",
      "Gluten-friendly + vegetarian options",
    ],
    phone: "(209) 457-8421",
    website: "https://www.tacobell.com",
    dietary: ["Vegetarian", "Vegan", "Gluten-friendly"],
    color: "#6A1B9A",
  },
  "Taco Villa": {
    emoji: "🌯",
    location: "Student Center",
    hours: { "Mon–Fri": "8am–8pm", "Sat–Sun": "Closed" },
    tags: ["Authentic SD taco shop"],
    deals: [
      "Authentic San Diego-style taco shop",
      "Opens at 8am — solid breakfast burrito",
    ],
    phone: "(858) 866-6339",
    website: "https://www.yelp.com/biz/taco-villa-san-diego",
    dietary: [],
    color: "#BF360C",
    inactive: true,
  },
  "Tapioca Express": {
    emoji: "🧋",
    location: "Price Center",
    hours: { "Mon–Fri": "9:30am–11pm", "Sat–Sun": "10:30am–11pm" },
    tags: ["Open until 11pm daily", "Vegetarian"],
    deals: [
      "Open 7 days a week until 11pm",
      "Full boba menu + Asian food",
      "Crispy calamari snack — fan favorite",
      "Specify spice level on most items",
    ],
    phone: "(858) 678-8821",
    website: "http://www.tapiocaexpress.com",
    dietary: ["Vegetarian"],
    color: "#00838F",
  },
  "TBD": {
    emoji: "❓",
    location: "TBD",
    hours: {},
    tags: [],
    deals: ["Vendor TBD — update when confirmed"],
    phone: "",
    website: "",
    dietary: [],
    color: "#9E9E9E",
  },
  "Yogurt World": {
    emoji: "🍦",
    location: "Student Services Center, Level 1",
    hours: { "Mon–Fri": "11am–9pm", "Sat": "11am–6pm", "Sun": "12pm–5pm" },
    tags: ["Vegetarian", "Vegan options", "Open 7 days"],
    deals: [
      "Fill-your-own cup — pay by weight",
      "Open 7 days including evenings",
    ],
    phone: "(858) 558-8989",
    website: "https://www.instagram.com/yogurtworld.ucsd",
    dietary: ["Vegetarian", "Vegan"],
    color: "#E91E63",
  },
  "Zanzibar Café at The Loft": {
    emoji: "🍷",
    location: "Price Center East, Level 2 — inside The Loft",
    hours: { "Mon–Fri": "10:30am–5pm", "Sat–Sun": "Closed" },
    tags: ["Alcohol served", "Most upscale on campus", "Live events"],
    deals: [
      "Happy Hour 3–5pm daily",
      "$6 HH items: Poke Nachos, Wings, Fish & Chips, Bratwurst, Flatbread Pizza, Taco Sampler",
      "Zanzibar Combo: half cold sandwich + soup for $12.50",
      "Local craft beer + wine list",
      "Live music via The Loft / ArtPower",
      "On-campus catering delivery available",
    ],
    phone: "(858) 678-0922",
    website: "https://zanzibarcafe.com",
    dietary: ["Vegetarian"],
    color: "#4A148C",
  },
};

export const VENDOR_NAMES = Object.keys(VENDORS).sort();
